# Generated by ariadne-codegen

from typing import Any, Optional

from . import HostingCapacityFileType, WorkflowStatus, ContainerType, SincalFileType, VariantFileType
from .custom_fields import (
    AppOptionsFields,
    CustomerDetailsResponseFields,
    DurationCurveByTerminalFields,
    FeederLoadAnalysisReportFields,
    GqlTxTapRecordFields,
    GqlUserFields,
    GqlUserResponseFields,
    HcCalibrationFields,
    HcScenarioConfigsPageFields,
    HcWorkPackageFields,
    HcWorkPackagePageFields,
    IngestionJobFields,
    IngestionRunFields,
    IngestorRunPageFields,
    JobSourceFields,
    MachineUserFields,
    MetricFields,
    NetworkModelsFields,
    OpenDssModelPageFields,
    OpportunitiesByYearFields,
    OpportunityFields,
    OpportunityLocationFields,
    PowerFactoryModelFields,
    PowerFactoryModelPageFields,
    PowerFactoryModelTemplateFields,
    PowerFactoryModelTemplatePageFields,
    ProcessedDiffFields,
    ProcessedDiffPageFields,
    SincalGlobalInputsConfigFields,
    SincalModelFields,
    SincalModelPageFields,
    SincalModelPresetFields,
    SincalModelPresetPageFields,
    StudyFields,
    StudyPageFields,
    StudyResultFields,
    UploadUrlResponseFields,
    UserCustomerListColumnConfigFields,
    VariantWorkPackageFields,
    WorkPackageTreeFields,
)
from .custom_typing_fields import GraphQLField
from .input_types import (
    GetOpenDssModelsFilterInput,
    GetOpenDssModelsSortCriteriaInput,
    GetPowerFactoryModelsFilterInput,
    GetPowerFactoryModelsSortCriteriaInput,
    GetPowerFactoryModelTemplatesFilterInput,
    GetPowerFactoryModelTemplatesSortCriteriaInput,
    GetSincalModelPresetsFilterInput,
    GetSincalModelPresetsSortCriteriaInput,
    GetSincalModelsFilterInput,
    GetSincalModelsSortCriteriaInput,
    GetStudiesFilterInput,
    GetStudiesSortCriteriaInput,
    HcScenarioConfigsFilterInput,
    HcWorkPackagesFilterInput,
    HcWorkPackagesSortCriteriaInput,
    IngestorRunsFilterInput,
    IngestorRunsSortCriteriaInput,
    ProcessedDiffFilterInput,
    ProcessedDiffSortCriteriaInput,
    WorkPackageInput,
)


class Query:
    @classmethod
    def paged_studies(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[GetStudiesFilterInput] = None,
        sort: Optional[GetStudiesSortCriteriaInput] = None
    ) -> StudyPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "GetStudiesFilterInput", "value": filter_},
            "sort": {"type": "GetStudiesSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return StudyPageFields(field_name="pagedStudies", arguments=cleared_arguments)

    @classmethod
    def results_by_id(cls, ids: list[str]) -> StudyResultFields:
        arguments: dict[str, dict[str, Any]] = {"ids": {"type": "[ID!]!", "value": ids}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return StudyResultFields(field_name="resultsById", arguments=cleared_arguments)

    @classmethod
    def studies(cls, *, filter_: Optional[GetStudiesFilterInput] = None) -> StudyFields:
        arguments: dict[str, dict[str, Any]] = {
            "filter": {"type": "GetStudiesFilterInput", "value": filter_}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return StudyFields(field_name="studies", arguments=cleared_arguments)

    @classmethod
    def studies_by_id(cls, ids: list[str]) -> StudyFields:
        arguments: dict[str, dict[str, Any]] = {"ids": {"type": "[ID!]!", "value": ids}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return StudyFields(field_name="studiesById", arguments=cleared_arguments)

    @classmethod
    def styles_by_id(cls, ids: list[str]) -> GraphQLField:
        arguments: dict[str, dict[str, Any]] = {"ids": {"type": "[ID!]!", "value": ids}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return GraphQLField(field_name="stylesById", arguments=cleared_arguments)

    @classmethod
    def current_user(cls) -> GqlUserResponseFields:
        return GqlUserResponseFields(field_name="currentUser")

    @classmethod
    def paged_power_factory_model_templates(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[GetPowerFactoryModelTemplatesFilterInput] = None,
        sort: Optional[GetPowerFactoryModelTemplatesSortCriteriaInput] = None
    ) -> PowerFactoryModelTemplatePageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {
                "type": "GetPowerFactoryModelTemplatesFilterInput",
                "value": filter_,
            },
            "sort": {
                "type": "GetPowerFactoryModelTemplatesSortCriteriaInput",
                "value": sort,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return PowerFactoryModelTemplatePageFields(
            field_name="pagedPowerFactoryModelTemplates", arguments=cleared_arguments
        )

    @classmethod
    def paged_power_factory_models(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[GetPowerFactoryModelsFilterInput] = None,
        sort: Optional[GetPowerFactoryModelsSortCriteriaInput] = None
    ) -> PowerFactoryModelPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "GetPowerFactoryModelsFilterInput", "value": filter_},
            "sort": {"type": "GetPowerFactoryModelsSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return PowerFactoryModelPageFields(
            field_name="pagedPowerFactoryModels", arguments=cleared_arguments
        )

    @classmethod
    def power_factory_model_by_id(cls, model_id: str) -> PowerFactoryModelFields:
        arguments: dict[str, dict[str, Any]] = {
            "modelId": {"type": "ID!", "value": model_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return PowerFactoryModelFields(
            field_name="powerFactoryModelById", arguments=cleared_arguments
        )

    @classmethod
    def power_factory_model_template_by_id(
        cls, template_id: str
    ) -> PowerFactoryModelTemplateFields:
        arguments: dict[str, dict[str, Any]] = {
            "templateId": {"type": "ID!", "value": template_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return PowerFactoryModelTemplateFields(
            field_name="powerFactoryModelTemplateById", arguments=cleared_arguments
        )

    @classmethod
    def power_factory_model_templates_by_ids(
        cls, template_ids: list[str]
    ) -> PowerFactoryModelTemplateFields:
        arguments: dict[str, dict[str, Any]] = {
            "templateIds": {"type": "[ID!]!", "value": template_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return PowerFactoryModelTemplateFields(
            field_name="powerFactoryModelTemplatesByIds", arguments=cleared_arguments
        )

    @classmethod
    def power_factory_models_by_ids(
        cls, model_ids: list[str]
    ) -> PowerFactoryModelFields:
        arguments: dict[str, dict[str, Any]] = {
            "modelIds": {"type": "[ID!]!", "value": model_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return PowerFactoryModelFields(
            field_name="powerFactoryModelsByIds", arguments=cleared_arguments
        )

    @classmethod
    def get_active_work_packages(cls) -> GraphQLField:
        return GraphQLField(field_name="getActiveWorkPackages")

    @classmethod
    def get_all_work_packages_authors(cls) -> GqlUserFields:
        return GqlUserFields(field_name="getAllWorkPackagesAuthors")

    @classmethod
    def get_calibration_run(cls, id: str) -> HcCalibrationFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return HcCalibrationFields(
            field_name="getCalibrationRun", arguments=cleared_arguments
        )

    @classmethod
    def get_calibration_sets(cls) -> GraphQLField:
        return GraphQLField(field_name="getCalibrationSets")

    @classmethod
    def get_duration_curves(
        cls,
        work_package_id: str,
        scenario: str,
        feeder: str,
        year: int,
        conducting_equipment_mrid: str,
    ) -> DurationCurveByTerminalFields:
        arguments: dict[str, dict[str, Any]] = {
            "workPackageId": {"type": "String!", "value": work_package_id},
            "scenario": {"type": "String!", "value": scenario},
            "feeder": {"type": "String!", "value": feeder},
            "year": {"type": "Int!", "value": year},
            "conductingEquipmentMrid": {
                "type": "String!",
                "value": conducting_equipment_mrid,
            },
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return DurationCurveByTerminalFields(
            field_name="getDurationCurves", arguments=cleared_arguments
        )

    @classmethod
    def get_opportunities(
        cls, *, year: Optional[int] = None
    ) -> OpportunitiesByYearFields:
        arguments: dict[str, dict[str, Any]] = {"year": {"type": "Int", "value": year}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return OpportunitiesByYearFields(
            field_name="getOpportunities", arguments=cleared_arguments
        )

    @classmethod
    def get_opportunities_for_equipment(cls, m_rid: str) -> OpportunityFields:
        arguments: dict[str, dict[str, Any]] = {
            "mRID": {"type": "String!", "value": m_rid}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return OpportunityFields(
            field_name="getOpportunitiesForEquipment", arguments=cleared_arguments
        )

    @classmethod
    def get_opportunity(cls, id: str) -> OpportunityFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "String!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return OpportunityFields(
            field_name="getOpportunity", arguments=cleared_arguments
        )

    @classmethod
    def get_opportunity_locations(
        cls, *, year: Optional[int] = None
    ) -> OpportunityLocationFields:
        arguments: dict[str, dict[str, Any]] = {"year": {"type": "Int", "value": year}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return OpportunityLocationFields(
            field_name="getOpportunityLocations", arguments=cleared_arguments
        )

    @classmethod
    def get_scenario_configurations(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[HcScenarioConfigsFilterInput] = None
    ) -> HcScenarioConfigsPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "HcScenarioConfigsFilterInput", "value": filter_},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return HcScenarioConfigsPageFields(
            field_name="getScenarioConfigurations", arguments=cleared_arguments
        )

    @classmethod
    def get_transformer_tap_settings(
        cls,
        calibration_name: str,
        *,
        feeder: Optional[str] = None,
        transformer_mrid: Optional[str] = None
    ) -> GqlTxTapRecordFields:
        arguments: dict[str, dict[str, Any]] = {
            "calibrationName": {"type": "String!", "value": calibration_name},
            "feeder": {"type": "String", "value": feeder},
            "transformerMrid": {"type": "String", "value": transformer_mrid},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return GqlTxTapRecordFields(
            field_name="getTransformerTapSettings", arguments=cleared_arguments
        )

    @classmethod
    def get_work_package_by_id(
        cls, id: str, *, with_groupings: Optional[bool] = None
    ) -> HcWorkPackageFields:
        arguments: dict[str, dict[str, Any]] = {
            "id": {"type": "ID!", "value": id},
            "withGroupings": {"type": "Boolean", "value": with_groupings},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return HcWorkPackageFields(
            field_name="getWorkPackageById", arguments=cleared_arguments
        )

    @classmethod
    def get_work_package_cost_estimation(cls, input: WorkPackageInput) -> GraphQLField:
        arguments: dict[str, dict[str, Any]] = {
            "input": {"type": "WorkPackageInput!", "value": input}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return GraphQLField(
            field_name="getWorkPackageCostEstimation", arguments=cleared_arguments
        )

    @classmethod
    def get_work_package_tree(cls, id: str) -> WorkPackageTreeFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "ID!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return WorkPackageTreeFields(
            field_name="getWorkPackageTree", arguments=cleared_arguments
        )

    @classmethod
    def get_work_packages(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[HcWorkPackagesFilterInput] = None,
        sort: Optional[HcWorkPackagesSortCriteriaInput] = None,
        with_groupings: Optional[bool] = None
    ) -> HcWorkPackagePageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "HcWorkPackagesFilterInput", "value": filter_},
            "sort": {"type": "HcWorkPackagesSortCriteriaInput", "value": sort},
            "withGroupings": {"type": "Boolean", "value": with_groupings},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return HcWorkPackagePageFields(
            field_name="getWorkPackages", arguments=cleared_arguments
        )

    @classmethod
    def hosting_capacity_file_upload_url(
        cls, filename: str, file_type: HostingCapacityFileType
    ) -> UploadUrlResponseFields:
        arguments: dict[str, dict[str, Any]] = {
            "filename": {"type": "String!", "value": filename},
            "fileType": {"type": "HostingCapacityFileType!", "value": file_type},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UploadUrlResponseFields(
            field_name="hostingCapacityFileUploadUrl", arguments=cleared_arguments
        )

    @classmethod
    def list_calibration_runs(
        cls,
        *,
        name: Optional[str] = None,
        calibration_time: Optional[Any] = None,
        status: Optional[WorkflowStatus] = None
    ) -> HcCalibrationFields:
        arguments: dict[str, dict[str, Any]] = {
            "name": {"type": "String", "value": name},
            "calibrationTime": {"type": "LocalDateTime", "value": calibration_time},
            "status": {"type": "WorkflowStatus", "value": status},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return HcCalibrationFields(
            field_name="listCalibrationRuns", arguments=cleared_arguments
        )

    @classmethod
    def get_processed_diff(cls, diff_id: str) -> ProcessedDiffFields:
        arguments: dict[str, dict[str, Any]] = {
            "diffId": {"type": "ID!", "value": diff_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ProcessedDiffFields(
            field_name="getProcessedDiff", arguments=cleared_arguments
        )

    @classmethod
    def get_processed_diffs(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[ProcessedDiffFilterInput] = None,
        sort: Optional[ProcessedDiffSortCriteriaInput] = None
    ) -> ProcessedDiffPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "ProcessedDiffFilterInput", "value": filter_},
            "sort": {"type": "ProcessedDiffSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return ProcessedDiffPageFields(
            field_name="getProcessedDiffs", arguments=cleared_arguments
        )

    @classmethod
    def get_all_jobs(cls) -> IngestionJobFields:
        return IngestionJobFields(field_name="getAllJobs")

    @classmethod
    def get_distinct_metric_names(cls, job_id: str) -> GraphQLField:
        arguments: dict[str, dict[str, Any]] = {
            "jobId": {"type": "String!", "value": job_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return GraphQLField(
            field_name="getDistinctMetricNames", arguments=cleared_arguments
        )

    @classmethod
    def get_metrics(
        cls, job_id: str, container_type: ContainerType, container_id: str
    ) -> MetricFields:
        arguments: dict[str, dict[str, Any]] = {
            "jobId": {"type": "String!", "value": job_id},
            "containerType": {"type": "ContainerType!", "value": container_type},
            "containerId": {"type": "String!", "value": container_id},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return MetricFields(field_name="getMetrics", arguments=cleared_arguments)

    @classmethod
    def get_newest_job(cls) -> IngestionJobFields:
        return IngestionJobFields(field_name="getNewestJob")

    @classmethod
    def get_sources(cls, job_id: str) -> JobSourceFields:
        arguments: dict[str, dict[str, Any]] = {
            "jobId": {"type": "String!", "value": job_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return JobSourceFields(field_name="getSources", arguments=cleared_arguments)

    @classmethod
    def paged_sincal_model_presets(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[GetSincalModelPresetsFilterInput] = None,
        sort: Optional[GetSincalModelPresetsSortCriteriaInput] = None
    ) -> SincalModelPresetPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "GetSincalModelPresetsFilterInput", "value": filter_},
            "sort": {"type": "GetSincalModelPresetsSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SincalModelPresetPageFields(
            field_name="pagedSincalModelPresets", arguments=cleared_arguments
        )

    @classmethod
    def paged_sincal_models(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[GetSincalModelsFilterInput] = None,
        sort: Optional[GetSincalModelsSortCriteriaInput] = None
    ) -> SincalModelPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "GetSincalModelsFilterInput", "value": filter_},
            "sort": {"type": "GetSincalModelsSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SincalModelPageFields(
            field_name="pagedSincalModels", arguments=cleared_arguments
        )

    @classmethod
    def sincal_model_by_id(cls, model_id: str) -> SincalModelFields:
        arguments: dict[str, dict[str, Any]] = {
            "modelId": {"type": "ID!", "value": model_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SincalModelFields(
            field_name="sincalModelById", arguments=cleared_arguments
        )

    @classmethod
    def sincal_model_config_upload_url(
        cls, filename: str, file_type: SincalFileType
    ) -> UploadUrlResponseFields:
        arguments: dict[str, dict[str, Any]] = {
            "filename": {"type": "String!", "value": filename},
            "fileType": {"type": "SincalFileType!", "value": file_type},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UploadUrlResponseFields(
            field_name="sincalModelConfigUploadUrl", arguments=cleared_arguments
        )

    @classmethod
    def sincal_model_global_config(cls) -> SincalGlobalInputsConfigFields:
        return SincalGlobalInputsConfigFields(field_name="sincalModelGlobalConfig")

    @classmethod
    def sincal_model_preset_by_id(cls, preset_id: str) -> SincalModelPresetFields:
        arguments: dict[str, dict[str, Any]] = {
            "presetId": {"type": "ID!", "value": preset_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SincalModelPresetFields(
            field_name="sincalModelPresetById", arguments=cleared_arguments
        )

    @classmethod
    def sincal_model_presets_by_ids(
        cls, preset_ids: list[str]
    ) -> SincalModelPresetFields:
        arguments: dict[str, dict[str, Any]] = {
            "presetIds": {"type": "[ID!]!", "value": preset_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SincalModelPresetFields(
            field_name="sincalModelPresetsByIds", arguments=cleared_arguments
        )

    @classmethod
    def sincal_models_by_ids(cls, model_ids: list[str]) -> SincalModelFields:
        arguments: dict[str, dict[str, Any]] = {
            "modelIds": {"type": "[ID!]!", "value": model_ids}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return SincalModelFields(
            field_name="sincalModelsByIds", arguments=cleared_arguments
        )

    @classmethod
    def create_machine_api_key(cls, roles: list[str], token_name: str) -> GraphQLField:
        arguments: dict[str, dict[str, Any]] = {
            "roles": {"type": "[String!]!", "value": roles},
            "tokenName": {"type": "String!", "value": token_name},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return GraphQLField(
            field_name="createMachineApiKey", arguments=cleared_arguments
        )

    @classmethod
    def create_user_api_key(cls, roles: list[str], token_name: str) -> GraphQLField:
        arguments: dict[str, dict[str, Any]] = {
            "roles": {"type": "[String!]!", "value": roles},
            "tokenName": {"type": "String!", "value": token_name},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return GraphQLField(field_name="createUserApiKey", arguments=cleared_arguments)

    @classmethod
    def get_machine_tokens(cls) -> MachineUserFields:
        return MachineUserFields(field_name="getMachineTokens")

    @classmethod
    def get_public_geo_view_config(cls) -> GraphQLField:
        return GraphQLField(field_name="getPublicGeoViewConfig")

    @classmethod
    def get_all_external_roles(cls) -> GraphQLField:
        return GraphQLField(field_name="getAllExternalRoles")

    @classmethod
    def get_network_models(cls) -> NetworkModelsFields:
        return NetworkModelsFields(field_name="getNetworkModels")

    @classmethod
    def get_feeder_load_analysis_report_status(
        cls, report_id: str, full_spec: bool
    ) -> FeederLoadAnalysisReportFields:
        arguments: dict[str, dict[str, Any]] = {
            "reportId": {"type": "ID!", "value": report_id},
            "fullSpec": {"type": "Boolean!", "value": full_spec},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return FeederLoadAnalysisReportFields(
            field_name="getFeederLoadAnalysisReportStatus", arguments=cleared_arguments
        )

    @classmethod
    def get_ingestor_run(cls, id: int) -> IngestionRunFields:
        arguments: dict[str, dict[str, Any]] = {"id": {"type": "Int!", "value": id}}
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return IngestionRunFields(
            field_name="getIngestorRun", arguments=cleared_arguments
        )

    @classmethod
    def list_ingestor_runs(
        cls,
        *,
        filter_: Optional[IngestorRunsFilterInput] = None,
        sort: Optional[IngestorRunsSortCriteriaInput] = None
    ) -> IngestionRunFields:
        arguments: dict[str, dict[str, Any]] = {
            "filter": {"type": "IngestorRunsFilterInput", "value": filter_},
            "sort": {"type": "IngestorRunsSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return IngestionRunFields(
            field_name="listIngestorRuns", arguments=cleared_arguments
        )

    @classmethod
    def list_ingestor_runs_paged(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[IngestorRunsFilterInput] = None,
        sort: Optional[IngestorRunsSortCriteriaInput] = None
    ) -> IngestorRunPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "IngestorRunsFilterInput", "value": filter_},
            "sort": {"type": "IngestorRunsSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return IngestorRunPageFields(
            field_name="listIngestorRunsPaged", arguments=cleared_arguments
        )

    @classmethod
    def paged_open_dss_models(
        cls,
        *,
        limit: Optional[int] = None,
        offset: Optional[Any] = None,
        filter_: Optional[GetOpenDssModelsFilterInput] = None,
        sort: Optional[GetOpenDssModelsSortCriteriaInput] = None
    ) -> OpenDssModelPageFields:
        arguments: dict[str, dict[str, Any]] = {
            "limit": {"type": "Int", "value": limit},
            "offset": {"type": "Long", "value": offset},
            "filter": {"type": "GetOpenDssModelsFilterInput", "value": filter_},
            "sort": {"type": "GetOpenDssModelsSortCriteriaInput", "value": sort},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return OpenDssModelPageFields(
            field_name="pagedOpenDssModels", arguments=cleared_arguments
        )

    @classmethod
    def get_user_permitted_customer_list_column_config(
        cls,
    ) -> UserCustomerListColumnConfigFields:
        return UserCustomerListColumnConfigFields(
            field_name="getUserPermittedCustomerListColumnConfig"
        )

    @classmethod
    def get_user_saved_customer_list_column_config(
        cls,
    ) -> UserCustomerListColumnConfigFields:
        return UserCustomerListColumnConfigFields(
            field_name="getUserSavedCustomerListColumnConfig"
        )

    @classmethod
    def get_customer_list(cls, m_ri_ds: list[str]) -> CustomerDetailsResponseFields:
        arguments: dict[str, dict[str, Any]] = {
            "mRIDs": {"type": "[String!]!", "value": m_ri_ds}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CustomerDetailsResponseFields(
            field_name="getCustomerList", arguments=cleared_arguments
        )

    @classmethod
    def get_customer_list_by_nmis(
        cls, nmis: list[str]
    ) -> CustomerDetailsResponseFields:
        arguments: dict[str, dict[str, Any]] = {
            "nmis": {"type": "[String!]!", "value": nmis}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return CustomerDetailsResponseFields(
            field_name="getCustomerListByNmis", arguments=cleared_arguments
        )

    @classmethod
    def get_app_options(cls) -> AppOptionsFields:
        return AppOptionsFields(field_name="getAppOptions")

    @classmethod
    def get_presigned_upload_url_for_variant(
        cls, filename: str, file_type: VariantFileType
    ) -> UploadUrlResponseFields:
        arguments: dict[str, dict[str, Any]] = {
            "filename": {"type": "String!", "value": filename},
            "fileType": {"type": "VariantFileType!", "value": file_type},
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return UploadUrlResponseFields(
            field_name="getPresignedUploadUrlForVariant", arguments=cleared_arguments
        )

    @classmethod
    def get_variant_upload_info(cls, job_id: str) -> VariantWorkPackageFields:
        arguments: dict[str, dict[str, Any]] = {
            "jobID": {"type": "String!", "value": job_id}
        }
        cleared_arguments = {
            key: value for key, value in arguments.items() if value["value"] is not None
        }
        return VariantWorkPackageFields(
            field_name="getVariantUploadInfo", arguments=cleared_arguments
        )
