# Generated by ariadne-codegen
# Source: http://127.0.0.1:7654/api/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CandidateGenerationType,
    HcFeederScenarioAllocationStrategy,
    HcLoadPlacement,
    HcSolveMode,
    HcSwitchClass,
    HcWriterType,
    IngestorRunState,
    IngestorRuntimeKind,
    InterventionClass,
    SectionType,
    SortOrder,
)


class AppOptionsInput(BaseModel):
    asset_name_format: Optional[str] = Field(alias="assetNameFormat", default=None)
    pole_string_format: Optional[str] = Field(alias="poleStringFormat", default=None)


class CandidateGenerationConfigInput(BaseModel):
    average_voltage_spread_threshold: Optional[int] = Field(
        alias="averageVoltageSpreadThreshold", default=None
    )
    intervention_criteria_name: Optional[str] = Field(
        alias="interventionCriteriaName", default=None
    )
    tap_weighting_factor_lower_threshold: Optional[float] = Field(
        alias="tapWeightingFactorLowerThreshold", default=None
    )
    tap_weighting_factor_upper_threshold: Optional[float] = Field(
        alias="tapWeightingFactorUpperThreshold", default=None
    )
    type_: CandidateGenerationType = Field(alias="type")
    voltage_over_limit_hours_threshold: Optional[int] = Field(
        alias="voltageOverLimitHoursThreshold", default=None
    )
    voltage_under_limit_hours_threshold: Optional[int] = Field(
        alias="voltageUnderLimitHoursThreshold", default=None
    )


class DvmsConfigInput(BaseModel):
    lower_limit: float = Field(alias="lowerLimit")
    lower_percentile: float = Field(alias="lowerPercentile")
    max_iterations: int = Field(alias="maxIterations")
    regulator_config: "DvmsRegulatorConfigInput" = Field(alias="regulatorConfig")
    upper_limit: float = Field(alias="upperLimit")
    upper_percentile: float = Field(alias="upperPercentile")


class DvmsRegulatorConfigInput(BaseModel):
    allow_push_to_limit: bool = Field(alias="allowPushToLimit")
    max_tap_change_per_step: int = Field(alias="maxTapChangePerStep")
    pu_deadband_percent: float = Field(alias="puDeadbandPercent")
    pu_target: float = Field(alias="puTarget")


class FeederConfigInput(BaseModel):
    feeder: str
    fixed_time: Optional["FixedTimeInput"] = Field(alias="fixedTime", default=None)
    scenarios: list[str]
    time_period: Optional["TimePeriodInput"] = Field(alias="timePeriod", default=None)
    years: list[int]


class FeederConfigsInput(BaseModel):
    configs: list["FeederConfigInput"]


class FeederLoadAnalysisInput(BaseModel):
    aggregate_at_feeder_level: bool = Field(alias="aggregateAtFeederLevel")
    end_date: str = Field(alias="endDate")
    feeders: Optional[list[str]] = None
    fetch_lv_network: bool = Field(alias="fetchLvNetwork")
    fla_forecast_config: Optional["FlaForecastConfigInput"] = Field(
        alias="flaForecastConfig", default=None
    )
    geographical_regions: Optional[list[str]] = Field(
        alias="geographicalRegions", default=None
    )
    output: Optional[str] = None
    process_coincident_loads: bool = Field(alias="processCoincidentLoads")
    process_feeder_loads: bool = Field(alias="processFeederLoads")
    produce_conductor_report: bool = Field(alias="produceConductorReport")
    start_date: str = Field(alias="startDate")
    sub_geographical_regions: Optional[list[str]] = Field(
        alias="subGeographicalRegions", default=None
    )
    substations: Optional[list[str]] = None


class FixedTimeInput(BaseModel):
    load_time: Any = Field(alias="loadTime")
    overrides: Optional[list["FixedTimeLoadOverrideInput"]] = None


class FixedTimeLoadOverrideInput(BaseModel):
    gen_var_override: Optional[list[float]] = Field(
        alias="genVarOverride", default=None
    )
    gen_watts_override: Optional[list[float]] = Field(
        alias="genWattsOverride", default=None
    )
    load_id: str = Field(alias="loadId")
    load_var_override: Optional[list[float]] = Field(
        alias="loadVarOverride", default=None
    )
    load_watts_override: Optional[list[float]] = Field(
        alias="loadWattsOverride", default=None
    )


class FlaForecastConfigInput(BaseModel):
    bess_upgrade_threshold: Optional[int] = Field(
        alias="bessUpgradeThreshold", default=None
    )
    pv_upgrade_threshold: Optional[int] = Field(
        alias="pvUpgradeThreshold", default=None
    )
    scenario_id: str = Field(alias="scenarioID")
    seed: Optional[int] = None
    year: int


class ForecastConfigInput(BaseModel):
    feeders: list[str]
    fixed_time: Optional["FixedTimeInput"] = Field(alias="fixedTime", default=None)
    scenarios: list[str]
    time_period: Optional["TimePeriodInput"] = Field(alias="timePeriod", default=None)
    years: list[int]


class GeoJsonOverlayInput(BaseModel):
    data: Any
    source_properties: Optional[Any] = Field(alias="sourceProperties", default=None)
    styles: list[str]


class GetOpenDssModelsFilterInput(BaseModel):
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    name: Optional[str] = None
    state: Optional[list[str]] = None


class GetOpenDssModelsSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    is_public: Optional[SortOrder] = Field(alias="isPublic", default=None)
    name: Optional[SortOrder] = None
    state: Optional[SortOrder] = None


class GetPowerFactoryModelTemplatesFilterInput(BaseModel):
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    name: Optional[str] = None


class GetPowerFactoryModelTemplatesSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    is_public: Optional[SortOrder] = Field(alias="isPublic", default=None)
    name: Optional[SortOrder] = None


class GetPowerFactoryModelsFilterInput(BaseModel):
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    name: Optional[str] = None
    state: Optional[list[str]] = None


class GetPowerFactoryModelsSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    is_public: Optional[SortOrder] = Field(alias="isPublic", default=None)
    name: Optional[SortOrder] = None
    state: Optional[SortOrder] = None


class GetSincalModelPresetsFilterInput(BaseModel):
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    name: Optional[str] = None


class GetSincalModelPresetsSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    is_public: Optional[SortOrder] = Field(alias="isPublic", default=None)
    name: Optional[SortOrder] = None


class GetSincalModelsFilterInput(BaseModel):
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    name: Optional[str] = None
    state: Optional[list[str]] = None


class GetSincalModelsSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    is_public: Optional[SortOrder] = Field(alias="isPublic", default=None)
    name: Optional[SortOrder] = None
    state: Optional[SortOrder] = None


class GetStudiesFilterInput(BaseModel):
    created_after: Optional[Any] = Field(alias="createdAfter", default=None)
    created_before: Optional[Any] = Field(alias="createdBefore", default=None)
    created_by: Optional[list[str]] = Field(alias="createdBy", default=None)
    id: Optional[str] = None
    name: Optional[str] = None
    tags: Optional[list[str]] = None


class GetStudiesSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    created_by: Optional[SortOrder] = Field(alias="createdBy", default=None)
    description: Optional[SortOrder] = None
    name: Optional[SortOrder] = None


class GqlDistributionTransformerConfigInput(BaseModel):
    r_ground: float = Field(alias="rGround")
    x_ground: float = Field(alias="xGround")


class GqlLoadConfigInput(BaseModel):
    spread_max_demand: bool = Field(alias="spreadMaxDemand")


class GqlScenarioConfigInput(BaseModel):
    bess_upgrade_threshold: int = Field(alias="bessUpgradeThreshold")
    pv_upgrade_threshold: int = Field(alias="pvUpgradeThreshold")
    scenario_id: str = Field(alias="scenarioID")
    years: list[int]


class GqlSincalModelForecastSpecInput(BaseModel):
    scenario_id: str = Field(alias="scenarioId")
    year: int


class HcEnhancedMetricsConfigInput(BaseModel):
    calculate_co_2: Optional[bool] = Field(alias="calculateCO2", default=None)
    calculate_emerg_for_gen_thermal: Optional[bool] = Field(
        alias="calculateEmergForGenThermal", default=None
    )
    calculate_emerg_for_load_thermal: Optional[bool] = Field(
        alias="calculateEmergForLoadThermal", default=None
    )
    calculate_normal_for_gen_thermal: Optional[bool] = Field(
        alias="calculateNormalForGenThermal", default=None
    )
    calculate_normal_for_load_thermal: Optional[bool] = Field(
        alias="calculateNormalForLoadThermal", default=None
    )
    populate_constraints: Optional[bool] = Field(
        alias="populateConstraints", default=None
    )
    populate_duration_curves: Optional[bool] = Field(
        alias="populateDurationCurves", default=None
    )
    populate_enhanced_metrics: Optional[bool] = Field(
        alias="populateEnhancedMetrics", default=None
    )
    populate_enhanced_metrics_profile: Optional[bool] = Field(
        alias="populateEnhancedMetricsProfile", default=None
    )
    populate_weekly_reports: Optional[bool] = Field(
        alias="populateWeeklyReports", default=None
    )


class HcExecutorConfigInput(BaseModel):
    value: Optional[str] = None


class HcGeneratorConfigInput(BaseModel):
    model: Optional["HcModelConfigInput"] = None
    node_level_results: Optional["HcNodeLevelResultsConfigInput"] = Field(
        alias="nodeLevelResults", default=None
    )
    raw_results: Optional["HcRawResultsConfigInput"] = Field(
        alias="rawResults", default=None
    )
    solve: Optional["HcSolveConfigInput"] = None


class HcInverterControlConfigInput(BaseModel):
    after_cut_off_profile: Optional[str] = Field(
        alias="afterCutOffProfile", default=None
    )
    before_cut_off_profile: Optional[str] = Field(
        alias="beforeCutOffProfile", default=None
    )
    cut_off_date: Optional[Any] = Field(alias="cutOffDate", default=None)


class HcMeterPlacementConfigInput(BaseModel):
    dist_transformers: Optional[bool] = Field(alias="distTransformers", default=None)
    energy_consumer_meter_group: Optional[str] = Field(
        alias="energyConsumerMeterGroup", default=None
    )
    feeder_head: Optional[bool] = Field(alias="feederHead", default=None)
    switch_meter_placement_configs: Optional[
        list["HcSwitchMeterPlacementConfigInput"]
    ] = Field(alias="switchMeterPlacementConfigs", default=None)


class HcMetricsResultsConfigInput(BaseModel):
    calculate_performance_metrics: Optional[bool] = Field(
        alias="calculatePerformanceMetrics", default=None
    )


class HcModelConfigInput(BaseModel):
    calibration: Optional[bool] = None
    closed_loop_time_delay: Optional[int] = Field(
        alias="closedLoopTimeDelay", default=None
    )
    closed_loop_v_band: Optional[float] = Field(alias="closedLoopVBand", default=None)
    closed_loop_v_limit: Optional[float] = Field(alias="closedLoopVLimit", default=None)
    closed_loop_v_reg_enabled: Optional[bool] = Field(
        alias="closedLoopVRegEnabled", default=None
    )
    closed_loop_v_reg_replace_all: Optional[bool] = Field(
        alias="closedLoopVRegReplaceAll", default=None
    )
    closed_loop_v_reg_set_point: Optional[float] = Field(
        alias="closedLoopVRegSetPoint", default=None
    )
    collapse_lv_networks: Optional[bool] = Field(
        alias="collapseLvNetworks", default=None
    )
    collapse_negligible_impedances: Optional[bool] = Field(
        alias="collapseNegligibleImpedances", default=None
    )
    collapse_swer: Optional[bool] = Field(alias="collapseSWER", default=None)
    combine_common_impedances: Optional[bool] = Field(
        alias="combineCommonImpedances", default=None
    )
    ct_prim_scaling_factor: Optional[float] = Field(
        alias="ctPrimScalingFactor", default=None
    )
    default_gen_var: Optional[list[float]] = Field(alias="defaultGenVar", default=None)
    default_gen_watts: Optional[list[float]] = Field(
        alias="defaultGenWatts", default=None
    )
    default_load_var: Optional[list[float]] = Field(
        alias="defaultLoadVar", default=None
    )
    default_load_watts: Optional[list[float]] = Field(
        alias="defaultLoadWatts", default=None
    )
    default_tap_changer_band: Optional[float] = Field(
        alias="defaultTapChangerBand", default=None
    )
    default_tap_changer_set_point_pu: Optional[float] = Field(
        alias="defaultTapChangerSetPointPu", default=None
    )
    default_tap_changer_time_delay: Optional[int] = Field(
        alias="defaultTapChangerTimeDelay", default=None
    )
    emerg_amp_scaling: Optional[float] = Field(alias="emergAmpScaling", default=None)
    feeder_scenario_allocation_strategy: Optional[
        HcFeederScenarioAllocationStrategy
    ] = Field(alias="feederScenarioAllocationStrategy", default=None)
    fix_overloading_consumers: Optional[bool] = Field(
        alias="fixOverloadingConsumers", default=None
    )
    fix_single_phase_loads: Optional[bool] = Field(
        alias="fixSinglePhaseLoads", default=None
    )
    fix_undersized_service_lines: Optional[bool] = Field(
        alias="fixUndersizedServiceLines", default=None
    )
    gen_v_max_pu: Optional[float] = Field(alias="genVMaxPu", default=None)
    gen_v_min_pu: Optional[float] = Field(alias="genVMinPu", default=None)
    inverter_control_config: Optional["HcInverterControlConfigInput"] = Field(
        alias="inverterControlConfig", default=None
    )
    load_interval_length_hours: Optional[float] = Field(
        alias="loadIntervalLengthHours", default=None
    )
    load_model: Optional[int] = Field(alias="loadModel", default=None)
    load_placement: Optional[HcLoadPlacement] = Field(
        alias="loadPlacement", default=None
    )
    load_v_max_pu: Optional[float] = Field(alias="loadVMaxPu", default=None)
    load_v_min_pu: Optional[float] = Field(alias="loadVMinPu", default=None)
    max_gen_tx_ratio: Optional[float] = Field(alias="maxGenTxRatio", default=None)
    max_load_lv_line_ratio: Optional[float] = Field(
        alias="maxLoadLvLineRatio", default=None
    )
    max_load_service_line_ratio: Optional[float] = Field(
        alias="maxLoadServiceLineRatio", default=None
    )
    max_load_tx_ratio: Optional[float] = Field(alias="maxLoadTxRatio", default=None)
    max_single_phase_load: Optional[float] = Field(
        alias="maxSinglePhaseLoad", default=None
    )
    meter_placement_config: Optional["HcMeterPlacementConfigInput"] = Field(
        alias="meterPlacementConfig", default=None
    )
    p_factor_base_exports: Optional[float] = Field(
        alias="pFactorBaseExports", default=None
    )
    p_factor_base_imports: Optional[float] = Field(
        alias="pFactorBaseImports", default=None
    )
    p_factor_forecast_pv: Optional[float] = Field(
        alias="pFactorForecastPv", default=None
    )
    rating_threshold: Optional[float] = Field(alias="ratingThreshold", default=None)
    seed: Optional[int] = None
    simplify_network: Optional[bool] = Field(alias="simplifyNetwork", default=None)
    simplify_plsi_threshold: Optional[float] = Field(
        alias="simplifyPLSIThreshold", default=None
    )
    split_phase_default_load_loss_percentage: Optional[float] = Field(
        alias="splitPhaseDefaultLoadLossPercentage", default=None
    )
    split_phase_lvkv: Optional[float] = Field(alias="splitPhaseLVKV", default=None)
    swer_voltage_to_line_voltage: Optional[list[list[int]]] = Field(
        alias="swerVoltageToLineVoltage", default=None
    )
    transformer_tap_settings: Optional[str] = Field(
        alias="transformerTapSettings", default=None
    )
    use_span_level_threshold: Optional[bool] = Field(
        alias="useSpanLevelThreshold", default=None
    )
    vm_pu: Optional[float] = Field(alias="vmPu", default=None)


class HcNodeLevelResultsConfigInput(BaseModel):
    collect_all_conductors: Optional[bool] = Field(
        alias="collectAllConductors", default=None
    )
    collect_all_energy_consumers: Optional[bool] = Field(
        alias="collectAllEnergyConsumers", default=None
    )
    collect_all_switches: Optional[bool] = Field(
        alias="collectAllSwitches", default=None
    )
    collect_all_transformers: Optional[bool] = Field(
        alias="collectAllTransformers", default=None
    )
    collect_current: Optional[bool] = Field(alias="collectCurrent", default=None)
    collect_power: Optional[bool] = Field(alias="collectPower", default=None)
    collect_voltage: Optional[bool] = Field(alias="collectVoltage", default=None)
    mrids_to_collect: Optional[list[str]] = Field(alias="mridsToCollect", default=None)


class HcRawResultsConfigInput(BaseModel):
    energy_meter_voltages_raw: Optional[bool] = Field(
        alias="energyMeterVoltagesRaw", default=None
    )
    energy_meters_raw: Optional[bool] = Field(alias="energyMetersRaw", default=None)
    overloads_raw: Optional[bool] = Field(alias="overloadsRaw", default=None)
    results_per_meter: Optional[bool] = Field(alias="resultsPerMeter", default=None)
    voltage_exceptions_raw: Optional[bool] = Field(
        alias="voltageExceptionsRaw", default=None
    )


class HcResultProcessorConfigInput(BaseModel):
    metrics: Optional["HcMetricsResultsConfigInput"] = None
    stored_results: Optional["HcStoredResultsConfigInput"] = Field(
        alias="storedResults", default=None
    )
    writer_config: Optional["HcWriterConfigInput"] = Field(
        alias="writerConfig", default=None
    )


class HcScenarioConfigsFilterInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class HcSolveConfigInput(BaseModel):
    base_frequency: Optional[int] = Field(alias="baseFrequency", default=None)
    emerg_v_max_pu: Optional[float] = Field(alias="emergVMaxPu", default=None)
    emerg_v_min_pu: Optional[float] = Field(alias="emergVMinPu", default=None)
    max_control_iter: Optional[int] = Field(alias="maxControlIter", default=None)
    max_iter: Optional[int] = Field(alias="maxIter", default=None)
    mode: Optional[HcSolveMode] = None
    norm_v_max_pu: Optional[float] = Field(alias="normVMaxPu", default=None)
    norm_v_min_pu: Optional[float] = Field(alias="normVMinPu", default=None)
    step_size_minutes: Optional[int] = Field(alias="stepSizeMinutes", default=None)
    voltage_bases: Optional[list[float]] = Field(alias="voltageBases", default=None)


class HcStoredResultsConfigInput(BaseModel):
    energy_meter_voltages_raw: Optional[bool] = Field(
        alias="energyMeterVoltagesRaw", default=None
    )
    energy_meters_raw: Optional[bool] = Field(alias="energyMetersRaw", default=None)
    overloads_raw: Optional[bool] = Field(alias="overloadsRaw", default=None)
    voltage_exceptions_raw: Optional[bool] = Field(
        alias="voltageExceptionsRaw", default=None
    )


class HcSwitchMeterPlacementConfigInput(BaseModel):
    meter_switch_class: HcSwitchClass = Field(alias="meterSwitchClass")
    name_pattern: str = Field(alias="namePattern")


class HcWorkPackagesFilterInput(BaseModel):
    created_by: Optional[list[str]] = Field(alias="createdBy", default=None)
    id: Optional[str] = None
    name: Optional[str] = None
    search_text: Optional[str] = Field(alias="searchText", default=None)


class HcWorkPackagesSortCriteriaInput(BaseModel):
    created_at: Optional[SortOrder] = Field(alias="createdAt", default=None)
    name: Optional[SortOrder] = None


class HcWriterConfigInput(BaseModel):
    output_writer_config: Optional["HcWriterOutputConfigInput"] = Field(
        alias="outputWriterConfig", default=None
    )
    writer_type: Optional[HcWriterType] = Field(alias="writerType", default=None)


class HcWriterOutputConfigInput(BaseModel):
    enhanced_metrics_config: Optional["HcEnhancedMetricsConfigInput"] = Field(
        alias="enhancedMetricsConfig", default=None
    )


class IngestorConfigInput(BaseModel):
    key: str
    value: str


class IngestorRunsFilterInput(BaseModel):
    completed: Optional[bool] = None
    container_runtime_type: Optional[list[IngestorRuntimeKind]] = Field(
        alias="containerRuntimeType", default=None
    )
    id: Optional[str] = None
    status: Optional[list[IngestorRunState]] = None


class IngestorRunsSortCriteriaInput(BaseModel):
    completed_at: Optional[SortOrder] = Field(alias="completedAt", default=None)
    container_runtime_type: Optional[SortOrder] = Field(
        alias="containerRuntimeType", default=None
    )
    started_at: Optional[SortOrder] = Field(alias="startedAt", default=None)
    status: Optional[SortOrder] = None
    status_last_updated_at: Optional[SortOrder] = Field(
        alias="statusLastUpdatedAt", default=None
    )


class InterventionConfigInput(BaseModel):
    allocation_criteria: Optional[str] = Field(alias="allocationCriteria", default=None)
    allocation_limit_per_year: Optional[int] = Field(
        alias="allocationLimitPerYear", default=None
    )
    base_work_package_id: str = Field(alias="baseWorkPackageId")
    candidate_generation: Optional["CandidateGenerationConfigInput"] = Field(
        alias="candidateGeneration", default=None
    )
    dvms: Optional["DvmsConfigInput"] = None
    intervention_type: InterventionClass = Field(alias="interventionType")
    phase_rebalance_proportions: Optional["PhaseRebalanceProportionsInput"] = Field(
        alias="phaseRebalanceProportions", default=None
    )
    specific_allocation_instance: Optional[str] = Field(
        alias="specificAllocationInstance", default=None
    )
    year_range: Optional["YearRangeInput"] = Field(alias="yearRange", default=None)


class OpenDssCommonConfigInput(BaseModel):
    fixed_time: Optional["FixedTimeInput"] = Field(alias="fixedTime", default=None)
    time_period: Optional["TimePeriodInput"] = Field(alias="timePeriod", default=None)


class OpenDssModelGenerationSpecInput(BaseModel):
    model_options: "OpenDssModelOptionsInput" = Field(alias="modelOptions")
    modules_configuration: "OpenDssModulesConfigInput" = Field(
        alias="modulesConfiguration"
    )


class OpenDssModelInput(BaseModel):
    generation_spec: "OpenDssModelGenerationSpecInput" = Field(alias="generationSpec")
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    model_name: Optional[str] = Field(alias="modelName", default=None)


class OpenDssModelOptionsInput(BaseModel):
    feeder: str
    scenario: str
    year: int


class OpenDssModulesConfigInput(BaseModel):
    common: "OpenDssCommonConfigInput"
    generator: Optional["HcGeneratorConfigInput"] = None


class PhaseRebalanceProportionsInput(BaseModel):
    a: float
    b: float
    c: float


class PowerFactoryModelGenerationSpecInput(BaseModel):
    distribution_transformer_config: Optional[
        "GqlDistributionTransformerConfigInput"
    ] = Field(alias="distributionTransformerConfig", default=None)
    equipment_container_mrids: list[str] = Field(alias="equipmentContainerMrids")
    load_config: Optional["GqlLoadConfigInput"] = Field(
        alias="loadConfig", default=None
    )
    model_name: Optional[str] = Field(alias="modelName", default=None)
    scenario_config: Optional["GqlScenarioConfigInput"] = Field(
        alias="scenarioConfig", default=None
    )


class PowerFactoryModelInput(BaseModel):
    generation_spec: "PowerFactoryModelGenerationSpecInput" = Field(
        alias="generationSpec"
    )
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    name: Optional[str] = None


class ProcessedDiffFilterInput(BaseModel):
    type_: Optional[str] = Field(alias="type", default=None)
    w_p_id: Optional[str] = Field(alias="wPId", default=None)


class ProcessedDiffSortCriteriaInput(BaseModel):
    type_: Optional[SortOrder] = Field(alias="type", default=None)
    work_packaged_id_1: Optional[SortOrder] = Field(
        alias="workPackagedId1", default=None
    )


class ResultSectionInput(BaseModel):
    columns: Any
    data: Any
    description: str
    name: str
    type_: SectionType = Field(alias="type")


class SincalModelGenerationSpecInput(BaseModel):
    equipment_container_mrids: Optional[list[str]] = Field(
        alias="equipmentContainerMrids", default=None
    )
    forecast_spec: Optional["GqlSincalModelForecastSpecInput"] = Field(
        alias="forecastSpec", default=None
    )
    frontend_config: str = Field(alias="frontendConfig")


class SincalModelInput(BaseModel):
    generation_spec: "SincalModelGenerationSpecInput" = Field(alias="generationSpec")
    is_public: Optional[bool] = Field(alias="isPublic", default=None)
    model_name: Optional[str] = Field(alias="modelName", default=None)


class StateOverlayInput(BaseModel):
    data: Any
    styles: list[str]


class StudyInput(BaseModel):
    description: str
    name: str
    results: list["StudyResultInput"]
    styles: list[Any]
    tags: list[str]


class StudyResultInput(BaseModel):
    geo_json_overlay: Optional["GeoJsonOverlayInput"] = Field(
        alias="geoJsonOverlay", default=None
    )
    name: str
    sections: list["ResultSectionInput"]
    state_overlay: Optional["StateOverlayInput"] = Field(
        alias="stateOverlay", default=None
    )


class TimePeriodInput(BaseModel):
    end_time: Any = Field(alias="endTime")
    overrides: Optional[list["TimePeriodLoadOverrideInput"]] = None
    start_time: Any = Field(alias="startTime")


class TimePeriodLoadOverrideInput(BaseModel):
    gen_var_override: Optional[list[float]] = Field(
        alias="genVarOverride", default=None
    )
    gen_watts_override: Optional[list[float]] = Field(
        alias="genWattsOverride", default=None
    )
    load_id: str = Field(alias="loadId")
    load_var_override: Optional[list[float]] = Field(
        alias="loadVarOverride", default=None
    )
    load_watts_override: Optional[list[float]] = Field(
        alias="loadWattsOverride", default=None
    )


class WorkPackageInput(BaseModel):
    executor_config: Optional["HcExecutorConfigInput"] = Field(
        alias="executorConfig", default=None
    )
    feeder_configs: Optional["FeederConfigsInput"] = Field(
        alias="feederConfigs", default=None
    )
    forecast_config: Optional["ForecastConfigInput"] = Field(
        alias="forecastConfig", default=None
    )
    generator_config: Optional["HcGeneratorConfigInput"] = Field(
        alias="generatorConfig", default=None
    )
    intervention: Optional["InterventionConfigInput"] = None
    quality_assurance_processing: Optional[bool] = Field(
        alias="qualityAssuranceProcessing", default=None
    )
    result_processor_config: Optional["HcResultProcessorConfigInput"] = Field(
        alias="resultProcessorConfig", default=None
    )


class YearRangeInput(BaseModel):
    max_year: int = Field(alias="maxYear")
    min_year: int = Field(alias="minYear")


DvmsConfigInput.model_rebuild()
FeederConfigInput.model_rebuild()
FeederConfigsInput.model_rebuild()
FeederLoadAnalysisInput.model_rebuild()
FixedTimeInput.model_rebuild()
ForecastConfigInput.model_rebuild()
HcGeneratorConfigInput.model_rebuild()
HcMeterPlacementConfigInput.model_rebuild()
HcModelConfigInput.model_rebuild()
HcResultProcessorConfigInput.model_rebuild()
HcWriterConfigInput.model_rebuild()
HcWriterOutputConfigInput.model_rebuild()
InterventionConfigInput.model_rebuild()
OpenDssCommonConfigInput.model_rebuild()
OpenDssModelGenerationSpecInput.model_rebuild()
OpenDssModelInput.model_rebuild()
OpenDssModulesConfigInput.model_rebuild()
PowerFactoryModelGenerationSpecInput.model_rebuild()
PowerFactoryModelInput.model_rebuild()
SincalModelGenerationSpecInput.model_rebuild()
SincalModelInput.model_rebuild()
StudyInput.model_rebuild()
StudyResultInput.model_rebuild()
TimePeriodInput.model_rebuild()
WorkPackageInput.model_rebuild()
