#  Copyright 2026 Zeppelin Bend Pty Ltd
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.

__all__ = ["EasClient"]

import ssl
from asyncio import get_event_loop
from datetime import datetime
from http import HTTPStatus

import httpx

from zepben.eas.client.decorators import async_func, catch_warnings
from zepben.eas.client.patched_generated_client import PatchedClient as Client

from zepben.eas.lib.generated_graphql_client import WorkPackageInput, FeederLoadAnalysisInput, StudyInput, \
    IngestorConfigInput, IngestorRunsFilterInput, IngestorRunsSortCriteriaInput, HcGeneratorConfigInput, \
    HcModelConfigInput, OpenDssModelInput, GetOpenDssModelsFilterInput, GetOpenDssModelsSortCriteriaInput
from zepben.eas.lib.generated_graphql_client.custom_fields import FeederLoadAnalysisSpecFields, \
    FeederLoadAnalysisReportFields, IngestionRunFields, HcCalibrationFields, GqlTxTapRecordFields, \
    OpenDssModelPageFields, OpenDssModelFields
from zepben.eas.lib.generated_graphql_client.custom_mutations import Mutation
from zepben.eas.lib.generated_graphql_client.custom_queries import Query


class EasClient:
    """
    A class used to represent a client to the Evolve App Server, with methods that represent requests to its API.
    """

    def __init__(
        self,
        host: str,
        port: int,
        protocol: str = "https",
        access_token: str | None = None,
        verify_certificate: bool = True,
        ca_filename: str | None = None,
        asynchronous: bool = False,
    ):
        """
        Construct a client for the Evolve App Server. If the server is HTTPS, authentication may be configured.
        Authentication may be configured by providing a personal access token or machine token to the access_token parameter.
        You can generate a personal access token from the profile page in the UI, or contact your EWB admin for a machine token
        if you are building a production service.

        Address parameters:
        :param host: The domain of the Evolve App Server, e.g. "evolve.local"
        :param port: The port on which to make requests to the Evolve App Server, e.g. 7624
        :param protocol: The protocol of the Evolve App Server. Should be either "http" or "https". Must be "https" if
                         auth is configured. (Defaults to "https")

        Authentication parameters:
        :param access_token: The access token used for authentication, generated by Evolve App Server. (Optional)

        HTTP/HTTPS parameters:
        :param verify_certificate: Set this to "False" to disable certificate verification.
        :param ca_filename: Path to CA file to use for verification. (Optional - by default will use system certs)
        :param asynchronous: all functions will be returned as ``Coroutine``s if True, or ran in an existing event loop if False
        """
        self._asynchronous = asynchronous
        self._protocol = protocol
        self._host = host
        self._port = port
        self._base_url = f"{protocol}://{host}:{port}"

        verify = False
        if verify_certificate:
            try:
                verify = ssl.create_default_context(cafile=ca_filename)
            except ssl.SSLError:
                verify = ssl.create_default_context(capath=ca_filename)

        http_client = httpx.AsyncClient(
            headers=dict(authorization=f"Bearer {access_token}") if access_token else None,
            verify=verify,
        )
        self._gql_client = Client(
            f"{self._base_url}/api/graphql",
            http_client=http_client,
        )


    def close(self):
        return get_event_loop().run_until_complete(self.aclose())

    async def aclose(self):  # FIXME: __axeit__ ?
        return

    @async_func
    @catch_warnings
    async def get_work_package_cost_estimation(self, work_package: WorkPackageInput):
        """
        Send request to hosting capacity service to get an estimate cost of supplied work package

        :param work_package: An instance of the `WorkPackageConfig` data class representing the work package configuration for the run
        :return: The HTTP response received from the Evolve App Server after attempting to run work package
        """
        return await self._gql_client.query(
            Query.get_work_package_cost_estimation(work_package),
            operation_name="getWorkPackageCostEstimation",
        )

    @async_func
    @catch_warnings
    async def run_hosting_capacity_work_package(self, work_package: WorkPackageInput, work_package_name: str):
        """
        Send request to hosting capacity service to run work package

        :param work_package: An instance of the `WorkPackageConfig` data class representing the work package configuration for the run
        :return: The HTTP response received from the Evolve App Server after attempting to run work package
        """
        return await self._gql_client.mutation(
            Mutation.run_work_package(work_package, work_package_name=work_package_name),
            operation_name="runWorkPackage",
        )

    @async_func
    @catch_warnings
    async def cancel_hosting_capacity_work_package(self, work_package_id: str):
        """
        Send request to hosting capacity service to cancel a running work package

        :param work_package_id: The id of the running work package to cancel
        :return: The HTTP response received from the Evolve App Server after attempting to cancel work package
        """
        return await self._gql_client.mutation(
            Mutation.cancel_work_package(work_package_id=work_package_id),
            operation_name="cancelWorkPackage"
        )

    def get_hosting_capacity_work_packages_progress(self):  # FIXME: why is this info not returned by get_work_package_by_id ?
        """
        Retrieve running work packages progress information from hosting capacity service

        :return: The HTTP response received from the Evolve App Server after requesting work packages progress info
        """
        raise NotImplementedError()
        return get_event_loop().run_until_complete(
            self._gql_client.query(
                Query.get_work_packages(),
                operation_name="getWorkPackagesProgres",
            )
        )

    @async_func
    @catch_warnings
    async def run_feeder_load_analysis_report(self, feeder_load_analysis_input: FeederLoadAnalysisInput):
        """
        Send request to evolve app server to run a feeder load analysis study

        :param feeder_load_analysis_input:: An instance of the `FeederLoadAnalysisConfig` data class representing the configuration for the run
        :return: The HTTP response received from the Evolve App Server after attempting to run work package
        """
        return await self._gql_client.mutation(
            Mutation.run_feeder_load_analysis(feeder_load_analysis_input),
            operation_name="runFeederLoadAnalysisReport"
        )

    @async_func
    @catch_warnings
    async def get_feeder_load_analysis_report_status(self, report_id: str, full_spec: bool = False):
        """
        Send request to evolve app server to retrieve a feeder load analysis report status

        :param report_id: Feeder load analysis report ID
        :param full_spec: If true the response will include the request sent to generate the report
        :return: The HTTP response received from the Evolve App Server after requesting a feeder load analysis report status
        """
        return await self._gql_client.query(
            Query.get_feeder_load_analysis_report_status(report_id, full_spec=full_spec).fields(
                FeederLoadAnalysisReportFields.id,
                FeederLoadAnalysisReportFields.name,
                FeederLoadAnalysisReportFields.created_at,
                FeederLoadAnalysisReportFields.created_by,
                FeederLoadAnalysisReportFields.completed_at,
                FeederLoadAnalysisReportFields.state,
                FeederLoadAnalysisReportFields.errors,
                FeederLoadAnalysisReportFields.generation_spec().fields(
                    FeederLoadAnalysisSpecFields.feeders,
                    FeederLoadAnalysisSpecFields.substations,
                    FeederLoadAnalysisSpecFields.sub_geographical_regions,
                    FeederLoadAnalysisSpecFields.geographical_regions,
                    FeederLoadAnalysisSpecFields.start_date,
                    FeederLoadAnalysisSpecFields.end_date,
                    FeederLoadAnalysisSpecFields.fetch_lv_network,
                    FeederLoadAnalysisSpecFields.process_feeder_loads,
                    FeederLoadAnalysisSpecFields.process_coincident_loads,
                    FeederLoadAnalysisSpecFields.produce_basic_report,
                    FeederLoadAnalysisSpecFields.produce_conductor_report,
                    FeederLoadAnalysisSpecFields.aggregate_at_feeder_level,
                    FeederLoadAnalysisSpecFields.output
                ),
            ),
            operation_name="getFeederLoadAnalysisReportStatus",
        )

    @async_func
    @catch_warnings
    async def upload_study(self, study: StudyInput | list[StudyInput]):
        """
        Uploads a new study to the Evolve App Server
        :param study: An instance of a data class representing a new study
        """
        return await self._gql_client.mutation(
            Mutation.add_studies(study if isinstance(study, list) else [study]),
            operation_name="addStudy",
        )

    @async_func
    @catch_warnings
    async def run_ingestor(self, run_config: list[IngestorConfigInput]):
        """
        Send request to perform an ingestor run
        :param run_config: A list of IngestorConfigInput
        :return: The HTTP response received from the Evolve App Server after attempting to run the ingestor
        """
        return await self._gql_client.mutation(
            Mutation.execute_ingestor(run_config=run_config),
            operation_name="executeIngestor",
        )

    @async_func
    @catch_warnings
    async def get_ingestor_run(self, ingestor_run_id: int):
        """
        Send request to retrieve the record of a particular ingestor run.
        :param ingestor_run_id: The ID of the ingestor run to retrieve execution information about.
        :return: The HTTP response received from the Evolve App Server including the ingestor run information (if found).
        """
        return await self._gql_client.query(
            Query.get_ingestor_run(ingestor_run_id).fields(
                IngestionRunFields.id,
                IngestionRunFields.container_runtime_type,
                IngestionRunFields.payload,
                IngestionRunFields.token,
                IngestionRunFields.status,
                IngestionRunFields.started_at,
                IngestionRunFields.status_last_updated_at,
                IngestionRunFields.completed_at,
            ),
            operation_name="getIngestorRun",
        )

    @async_func
    @catch_warnings
    async def get_ingestor_run_list(
            self,
            query_filter: IngestorRunsFilterInput | None = None,
            query_sort: IngestorRunsSortCriteriaInput | None = None
    ):
        """
        Send request to retrieve a list of ingestor run records matching the provided filter parameters.
        :param query_filter: An `IngestorRunsFilterInput` object. Only records matching the provided values will be returned.
            If not supplied all records will be returned. (Optional)
        :param query_sort: An `IngestorRunsSortCriteriaInput` that can control the order of the returned record based on a number of fields. (Optional)
        :return: The HTTP response received from the Evolve App Server including all matching ingestor records found.
        """
        return await self._gql_client.query(
            Query.list_ingestor_runs(filter_=query_filter, sort=query_sort).fields(
                IngestionRunFields.id,
                IngestionRunFields.container_runtime_type,
                IngestionRunFields.payload,
                IngestionRunFields.token,
                IngestionRunFields.status,
                IngestionRunFields.started_at,
                IngestionRunFields.status_last_updated_at,
                IngestionRunFields.completed_at,
            ),
            operation_name="listIngestorRuns",
        )

    @async_func
    @catch_warnings
    async def run_hosting_capacity_calibration(
            self,
            calibration_name: str,
            local_calibration_time: datetime,
            feeders: list[str] | None = None,
            transformer_tap_settings: str | None = None,
            generator_config: HcGeneratorConfigInput | None = None):
        """
        Send request to run hosting capacity calibration
        :param calibration_name: A string representation of the calibration name
        :param local_calibration_time: A datetime representation of the calibration time, in the timezone of your pqv data ("model time").
        :param feeders: A list of feeder ID's to run the calibration over. If not supplied then the calibration is run over all feeders in the network.
        :param transformer_tap_settings: A set of transformer tap settings to apply before running the calibration work package.
                If provided, this will take precedence over any 'transformer_tap_settings' supplied in via the generator_config parameter
        :param generator_config: A `GeneratorConfig` object that overrides the default values in the `WorkPackageConfig` used by calibration.
                Note: The following fields cannot be overridden during calibration: generator_config.model.calibration, generator_config.model.meter_placement_config, generator_config.solve.step_size_minutes, and generator_config.raw_results.


        :return: The HTTP response received from the Evolve App Server after attempting to run the calibration
        """
        if transformer_tap_settings:
            if generator_config is None:
                generator_config = HcGeneratorConfigInput()
            if generator_config.model is None:
                generator_config.model = HcModelConfigInput()
            if generator_config.model:
                generator_config.model.transformer_tap_settings = transformer_tap_settings

        return await self._gql_client.mutation(
            Mutation.run_calibration(
                calibration_name=calibration_name,
                calibration_time_local=local_calibration_time,
                feeders=feeders,
                generator_config=generator_config,
            ),
            operation_name="runCalibration",
        )

    @async_func
    @catch_warnings
    async def get_hosting_capacity_calibration_run(self, id: str):
        """
        Retrieve information of a hosting capacity calibration run
        :param id: The calibration run ID
        :return: The HTTP response received from the Evolve App Server after requesting calibration run info
        """
        return await self._gql_client.query(
            Query.get_calibration_run(id).fields(
                HcCalibrationFields.id,
                HcCalibrationFields.name,
                HcCalibrationFields.workflow_id,
                HcCalibrationFields.run_id,
                HcCalibrationFields.calibration_time_local,
                HcCalibrationFields.start_at,
                HcCalibrationFields.completed_at,
                HcCalibrationFields.status,
                HcCalibrationFields.feeders,
                HcCalibrationFields.calibration_work_package_config,
            ),
            operation_name="getCalibrationRun",
        )

    @async_func
    @catch_warnings
    async def get_hosting_capacity_calibration_sets(self):
        """
        Retrieve a list of all completed calibration runs initiated through Evolve App Server
        :return: The HTTP response received from the Evolve App Server after requesting completed calibration runs
        """
        return await self._gql_client.query(
            Query.get_calibration_sets(),
            operation_name="getCalibrationSets",
        )

    @async_func
    @catch_warnings
    async def get_transformer_tap_settings(
            self,
            calibration_name: str,
            feeder: str | None = None,
            transformer_mrid: str | None = None
    ):
        """
        Retrieve distribution transformer tap settings from a calibration set in the hosting capacity input database
        :param calibration_name: The (user supplied)name of the calibration run to retrieve transformer tap settings from
        :param feeder: An optional filter to apply to the returned list of transformer tap settings
        :param transformer_mrid: An optional filter to return only the transformer tap settings for a particular transfomer mrid
        :return: The HTTP response received from the Evolve App Server after requesting transformer tap settings for the calibration id
        """
        return await self._gql_client.query(
            Query.get_transformer_tap_settings(
                calibration_name=calibration_name,
                feeder=feeder,
                transformer_mrid=transformer_mrid
            ).fields(
                GqlTxTapRecordFields.id,
                GqlTxTapRecordFields.high_step,
                GqlTxTapRecordFields.low_step,
                GqlTxTapRecordFields.nominal_tap_num,
                GqlTxTapRecordFields.tap_position,
                GqlTxTapRecordFields.control_enabled,
                GqlTxTapRecordFields.step_voltage_increment,
            ),
            operation_name="getTransformerTapSettings",
        )

    @async_func
    @catch_warnings
    async def run_opendss_export(self, config: OpenDssModelInput):
        """
        Send request to run an opendss export
        :param config: The OpenDssConfig for running the export
        :return: The HTTP response received from the Evolve App Server after attempting to run the opendss export
        """
        return await self._gql_client.mutation(
            Mutation.create_open_dss_model(config),
            operation_name="createOpenDssModel",
        )

    @async_func
    @catch_warnings
    async def get_paged_opendss_models(
        self,
        limit: int | None = None,
        offset: int | None = None,
        query_filter: GetOpenDssModelsFilterInput | None = None,
        query_sort: GetOpenDssModelsSortCriteriaInput | None = None):
        """
        Retrieve a paginated opendss export run information
        :param limit: The number of opendss export runs to retrieve
        :param offset: The number of opendss export runs to skip
        :param query_filter: The filter to apply to the query
        :param query_sort: The sorting to apply to the query
        :return: The HTTP response received from the Evolve App Server after requesting opendss export run information
        """
        return await self._gql_client.query(
            Query.paged_open_dss_models(
                limit=limit,
                offset=offset,
                filter_=query_filter,
                sort=query_sort
            ).fields(
                OpenDssModelPageFields.total_count,
                OpenDssModelPageFields.offset,
                OpenDssModelPageFields.models().fields(
                    OpenDssModelFields.id,
                    OpenDssModelFields.name,
                    OpenDssModelFields.created_at,
                    OpenDssModelFields.state,
                    OpenDssModelFields.download_url,
                    OpenDssModelFields.is_public,
                    OpenDssModelFields.errors,
                    OpenDssModelFields.generation_spec
                ),
            ),
            operation_name="pagedOpenDssModels",
        )

    @async_func
    @catch_warnings
    async def get_opendss_model_download_url(self, run_id: int):
        """
        Retrieve a download url for the specified opendss export run id
        :param run_id: The opendss export run ID
        :return: The HTTP response received from the Evolve App Server after requesting opendss export model download url
        """
        response = (await self._gql_client.http_client.get(
            f"{self._base_url}/api/opendss-model/{run_id}",
            headers=self._gql_client.headers,
            follow_redirects=False
        ))
        if response.status_code == HTTPStatus.FOUND:
            return response.headers["Location"]
        elif not response.ok:
            response.raise_for_status()

    @async_func
    @catch_warnings
    async def get_opendss_model(self, model_id: int):
        """
        Retrieve information of a OpenDss model export
        :param model_id: The OpenDss model export ID
        :return: The HTTP response received from the Evolve App Server after requesting the openDss model info
        """

        offset = 0
        page_size = 20

        while True:
            response = await self.get_paged_opendss_models(page_size, offset)
            total_count = int(response["data"]["pagedOpenDssModels"]["totalCount"])
            page_count = len(response["data"]["pagedOpenDssModels"]["models"])
            for model in response["data"]["pagedOpenDssModels"]["models"]:
                if model["id"] == model_id:
                    return model
            offset += page_count

            if offset >= total_count:
                break

        raise ValueError(f"Model id:{model_id} was not found in EAS database.")
