#  Copyright 2026 Zeppelin Bend Pty Ltd
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.

from typing import Any, cast

import httpx
from ariadne_codegen.client_generators.dependencies.exceptions import GraphQLClientHttpError, \
    GraphQLClientInvalidResponseError, GraphQLClientGraphQLMultiError

from zepben.eas.lib.generated_graphql_client import Client


class PatchedClient(Client):
    """
    Used to override autogenerated client code, rather than having to maintain a diff to be applied after generating.
    """

    def get_data(self, response: httpx.Response) -> dict[str, Any]:
        if not response.is_success:
            raise GraphQLClientHttpError(
                status_code=response.status_code, response=response
            )

        try:
            response_json = response.json()
        except ValueError as exc:
            raise GraphQLClientInvalidResponseError(response=response) from exc

        try:
            errors = response_json.get("errors")
        except AttributeError:
            errors = None

        if errors:
            raise GraphQLClientGraphQLMultiError.from_errors_dicts(
                errors_dicts=errors, data=response_json
            )

        return cast(dict[str, Any], response_json)
