name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  licence-check:
    runs-on: ubuntu-latest
    container: python:3.7-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add tar curl bash

      - name: Cache licence-check
        uses: actions/cache@v2
        with:
          path: /lc
          key: lcc

      - name: Check licence
        uses: zepben/licence-check-action@main
        with:
          LC_URL: ${{ secrets.LC_URL }}

      - name: Cache python deps
        uses: actions/cache@v2
        with:
          path: /pipcache
          key: pip

      - name: Build and publish
        run: |
          mkdir -p /pipcache
          pip install --cache-dir /pipcache -r requirements.txt
          python setup.py sdist bdist_wheel
        shell: bash
